trigger:
   batch: true
  # branches:
  #   include:
  #     - main

pr:
  branches:
    include:
      - main

pool:
  name: 'Azure Pipelines'

lockBehavior: sequential
stages:
- stage: BuildandDeployStage
  jobs:
  - job: BuildAndDeploy
    displayName: 'Build and Deploy Job'
    strategy:
      parallel: 0
    steps:
    # - task: AzureStaticWebApp@0
    #   inputs:
    #     app_location: '/src'
    #     api_location: 'api'
    #     output_location: '/src'
    #     azure_static_web_apps_api_token: $(deployment_token)
    #     repo_token: $(GITHUB_TOKEN)
    #     action: 'upload'
    - task: CmdLine@2
      inputs:
        script: 'echo "BuildandDeploy"'
- stage: ExecuteCommands
  dependsOn: BuildandDeployStage
  jobs:
  - job: ExecuteCommands
    displayName: 'Execute Commands'
    strategy:
      parallel: 0
    steps:
    - task: CmdLine@2
      inputs:
        script: 'echo "Hello"'
  

# - job: ClosePullRequest
#   displayName: 'Close Pull Request Job'
#   pool:
#     vmImage: 'ubuntu-latest'
#   steps:
#   - task: AzureStaticWebApp@0
#     inputs:
#       azure_static_web_apps_api_token: $(deployment_token)
#       action: 'close'
  # - task: PublishPipelineArtifact@1
  #   inputs:
  #     targetPath: '$(Pipeline.Workspace)'
  #     artifact: 'Demo'
  #     publishLocation: 'pipeline'