# resources:
#   repositories:
#   - repository: sre-pipeline
#     type: git
#     name: SRE.Builds
#   - repository: srcDevRepo
#     path: $(Build.SourcesDirectory)
#     type: git
#     name: ocp-cluster-observability
pr:
  branches:
    include:
    - main
 
trigger:
  branches:
    include:
    - main
  
pool:
    vmImage: ubuntu-latest
steps:
- task: Bash@3
  inputs:
    targetType: 'inline'
    script: |
      # Write your commands here
      echo 'Hello world'
 
