trigger:
  branches:
    include:
      - main

pr:
  branches:
    include:
      - main

jobs:
- job: BuildAndDeploy
  displayName: 'Build and Deploy Job'
  pool:
    vmImage: 'ubuntu-latest'
  steps:
  - task: AzureStaticWebApp@0
    inputs:
      app_location: '/src'
      api_location: 'api'
      output_location: '/src'
      azure_static_web_apps_api_token: $(deployment_token)
      repo_token: $(GITHUB_TOKEN)
      action: 'upload'
  - task: UniversalPackages@0
    inputs:
      command: 'publish'
      publishDirectory: '$(Build.ArtifactStagingDirectory)'
      feedsToUsePublish: 'internal'
      vstsFeedPublish: 'a11ce107-282f-44fe-b716-51be402640eb'
      versionOption: 'major'

# - job: ClosePullRequest
#   displayName: 'Close Pull Request Job'
#   pool:
#     vmImage: 'ubuntu-latest'
#   steps:
#   - task: AzureStaticWebApp@0
#     inputs:
#       azure_static_web_apps_api_token: $(deployment_token)
#       action: 'close'