trigger:
  branches:
    include:
      - main

pr:
  branches:
    include:
      - main

jobs:
- job: BuildAndDeploy
  displayName: 'Build and Deploy Job'
  pool:
    vmImage: 'ubuntu-latest'
  condition: or(eq(variables['Build.SourceBranch'], 'refs/heads/main'), and(eq(variables['Build.Reason'], 'PullRequest'), ne(variables['System.PullRequest.IsDraft'], 'true')))
  steps:
  - task: AzureStaticWebApp@0
    inputs:
      app_location: '/src'
      api_location: 'api'
      output_location: '/src'
      azure_static_web_apps_api_token: $(AZURE_STATIC_WEB_APPS_API_TOKEN_ICY_WATER_08738BB0F)
      repo_token: $(GITHUB_TOKEN)
      action: 'upload'

- job: ClosePullRequest
  displayName: 'Close Pull Request Job'
  pool:
    vmImage: 'ubuntu-latest'
  condition: and(eq(variables['Build.Reason'], 'PullRequest'), eq(variables['System.PullRequest.IsDraft'], 'true'))
  steps:
  - task: AzureStaticWebApp@0
    inputs:
      azure_static_web_apps_api_token: $(AZURE_STATIC_WEB_APPS_API_TOKEN_ICY_WATER_08738BB0F)
      action: 'close'