trigger:
   batch: true
  # branches:
  #   include:
  #     - main

pr:
  branches:
    include:
      - main

pool:
  vmImage: 'windows-latest'

lockBehavior: sequential
stages:
# - stage: BuildandDeployStage
#   jobs:
#   - job: BuildAndDeploy
#     displayName: 'Build and Deploy Job'
    #pool: server
    #steps:
    # - task: AzureStaticWebApp@0
    #   inputs:
    #     app_location: '/src'
    #     api_location: 'api'
    #     output_location: '/src'
    #     azure_static_web_apps_api_token: $(deployment_token)
    #     repo_token: $(GITHUB_TOKEN)
    #     action: 'upload'
    # - task: ManualValidation@1
    #   inputs:
    #     notifyUsers: 'sagpatel@microsoft.com'
    #     approvers: 'sagpatel@microsoft.com'
    #     allowApproversToApproveTheirOwnRuns: true
    # - task: CmdLine@2
    #   inputs:
    #     script: 'echo "BuildandDeploy"'
  #- stage: ExecuteCommands
    # dependsOn: BuildandDeployStage
    #jobs:
    # - job: ExecuteCommands
    #   displayName: 'Execute Commands'
    #   strategy:
    #     parallel: 0
    - stage: SendEmail
      jobs:
       - job: BuildAndDeploy
         steps:
          - task: CmdLine@2
            inputs:
              script: 'echo "Hello"'
          - task: Bash@3
            inputs:
              targetType: 'inline'
              script: |
                # Send an email with the file attached
                echo "The file has been generated and stored on the self-hosted agent. Please find the attached file." | mail -s "Pipeline File" -a /path/to/self-hosted-agent/directory/yourfile_part_* sagpatel@microsoft.com

          # - task: SendEmail@1
          #   inputs:              
          #     To: 'sagpatel@microsoft.com'
          #     From: 'sagpatel@microsoft.com'
          #     Subject: 'Pipeline File'
          #     Body: 'The file has been uploaded. You can download it from the following link: https://your-storage-account.blob.core.windows.net/your-container/your-blob-prefix/yourfile.zip'

  

# - job: ClosePullRequest
#   displayName: 'Close Pull Request Job'
#   pool:
#     vmImage: 'ubuntu-latest'
#   steps:
#   - task: AzureStaticWebApp@0
#     inputs:
#       azure_static_web_apps_api_token: $(deployment_token)
#       action: 'close'
  # - task: PublishPipelineArtifact@1
  #   inputs:
  #     targetPath: '$(Pipeline.Workspace)'
  #     artifact: 'Demo'
  #     publishLocation: 'pipeline'