trigger:
  branches:
    include:
      - main

pr:
  branches:
    include:
      - main

jobs:
- job: BuildAndDeploy
  displayName: 'Build and Deploy Job'
  pool:
    name: 'Self-hosted' 
  steps:
  # - task: AzureStaticWebApp@0
  #   inputs:
  #     app_location: '/src'
  #     api_location: 'api'
  #     output_location: '/src'
  #     azure_static_web_apps_api_token: $(deployment_token)
  #     repo_token: $(GITHUB_TOKEN)
  #     action: 'upload'
  - task: CmdLine@2
    inputs:
      script: |
        //echo 'Hi'
        echo 'Hello world'
# - job: ClosePullRequest
#   displayName: 'Close Pull Request Job'
#   pool:
#     vmImage: 'ubuntu-latest'
#   steps:
#   - task: AzureStaticWebApp@0
#     inputs:
#       azure_static_web_apps_api_token: $(deployment_token)
#       action: 'close'
  # - task: PublishPipelineArtifact@1
  #   inputs:
  #     targetPath: '$(Pipeline.Workspace)'
  #     artifact: 'Demo'
  #     publishLocation: 'pipeline'