# resources:
#   repositories:
#   - repository: sre-pipeline
#     type: git
#     name: SRE.Builds
#   - repository: srcDevRepo
#     path: $(Build.SourcesDirectory)
#     type: git
#     name: ocp-cluster-observability
trigger: none
#name: $(Build.DefinitionName)_$(semVersion)$(Rev:.r)
parameters:
- name: validateVarsOnly
  type: boolean
  default: false
- name: multiParallelEnv
  type: boolean
  default: true
  
pool:
    vmImage: ubuntu-latest

variables:
- name: semVersion
  value: 1.0

stages:
  - stage: OpenshiftDev02__openshift_cluster_observability_operator__cluster_observability_operator__
    displayName: Openshift Dev02 - cluster-observability-operator
    jobs:
      - job: BuildJob
        steps:
          - script: echo "Building..."
  - stage: OpenshiftDev01__openshift_cluster_observability_operator__cluster_observability_operator__
    displayName: Openshift Dev01 - cluster-observability-operator
    dependsOn: []
    pool:
      vmImage: ubuntu-latest
    jobs:
      - job: BuildJob1
        steps:
          - script: echo "Building1..."
 
